banco_comercial/banco_comercial/urls.py
from django.contrib import admin
from django.urls import include, path
from principal import urls as principal_urls 
urlpatterns = [
    path("user/", include("contas.urls", namespace='contas')),
    path("admin/", admin.site.urls),
    path('', include((principal_urls, 'principal'), namespace='principal')),
    path('client/', include('dashboard.urls', namespace='dashboard')),

]

banco_comercial/contas/urls.py
from django.urls import path
from .views import cadastro_view, poscadastro_view,redict_home, login_view
app_name = 'contas'
urlpatterns = [
    path('cadastro/', cadastro_view, name='cadastro_view'),
    path('pos/', poscadastro_view, name='poscadastro_view'),
    path('login/', login_view, name='login_view'),
    path('redict_home/', redict_home, name='redict_home'),

    # ... outras URLs ...
]

banco_comercial/dashboard/urls.py
from django.urls import path
from .views import (
    dados_view,
    extrato_view,
    pagar_view,
    transferir_view,
    investir_view,
    emprestimo_view,
    saldo_view,
    notificacoes_view,
    configuracoes_view,
    cartoes_view,
)

app_name = 'dashboard'

urlpatterns = [
    path('dados/', dados_view, name='dados_view'),
    path('extrato/', extrato_view, name='extrato_view'),
    path('pagar/', pagar_view, name='pagar_view'),
    path('transferir/', transferir_view, name='transferir_view'),
    path('investir/', investir_view, name='investir_view'),
    path('emprestimo/', emprestimo_view, name='emprestimo_view'),
    path('saldo/', saldo_view, name='saldo_view'),
    path('notificacoes/', notificacoes_view, name='notificacoes_view'),
    path('configuracoes/', configuracoes_view, name='configuracoes_view'),
    path('cartoes/', cartoes_view, name='cartoes_view'),
]

banco_comercial/principal/urls.py
from django.urls import path
from .views import home_view

app_name = 'principal'
urlpatterns = [
    path('', home_view, name='home_view'),
    # path('redict_for_login/', login_view_redict, name='login_view_redict'),
    # ... outras URLs ...
]

banco_comercial/dashboard/models.py
from django.db import models

# Create your models here.
# dashboard/models.py
from django.db import models
from django.contrib.auth.models import User  # Se você estiver usando autenticação de usuário do Django


# Cartão
class CartaoDebito(models.Model):
    nome = models.CharField(max_length=255)
    numero = models.CharField(max_length=16)
    titular = models.CharField(max_length=255)
    data_vencimento = models.DateField()

class CartaoCredito(models.Model):
    nome = models.CharField(max_length=255)
    numero = models.CharField(max_length=16)
    titular = models.CharField(max_length=255)
    data_vencimento = models.DateField()
# ========


class Configuracao(models.Model):
    # Campos específicos para a tela de configuração
    opcao1 = models.CharField(max_length=255)
    # Adicione outros campos necessários

class Dados(models.Model):
    # Campos específicos para a tela de dados
    informacao1 = models.CharField(max_length=255)
    # Adicione outros campos necessários

class Emprestimo(models.Model):
    # Campos específicos para a tela de empréstimo
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    # Adicione outros campos necessários

# Adicione modelos para as outras telas (Extrato, Investir, Notificações, Pagamento, Transferir, etc.)

banco_comercial/principal/models.py
from django.db import models

# Create your models here.

banco_comercial/dashboard/views.py
from django.shortcuts import render
from contas.models import PerfilUsuario
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from django.shortcuts import redirect
from django.shortcuts import render, redirect
from contas.models import PerfilUsuario
from django.contrib.auth.decorators import login_required
# Create your views here.

def get(self, request, *args, **kwargs):
        # Obtenha o perfil do usuário diretamente usando self.request.user
        usuario = self.request.user
        try:
            # Certifique-se de que o campo correto seja usado ('nome' em vez de 'usuario')
            perfil_usuario = PerfilUsuario.objects.get(nome=usuario)
            context = {'user_profile': perfil_usuario}
        except PerfilUsuario.DoesNotExist:
            # Lide com o caso em que o perfil do usuário não existe
            context = {'user_profile': None}
class UserProfileMixin:
    template_name = None  # Substitua por seu template desejado

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        usuario = self.request.user
        try:
            perfil_usuario = PerfilUsuario.objects.get(nome=usuario)
            context['user_profile'] = perfil_usuario
        except PerfilUsuario.DoesNotExist:
            context['user_profile'] = None

        return context

    def post(self, request, *args, **kwargs):
        # Lógica para lidar com um pedido POST
        # Por exemplo, atualizar as configurações do usuário
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        
        # Lógica para atualizar os dados do usuário no banco de dados

        return redirect('dashboard:configuracoes_view')



def dados_view(request):
    usuario = request.user
    try:
        perfil_usuario = PerfilUsuario.objects.get(nome=usuario)
        context = {'user_profile': perfil_usuario}
    except PerfilUsuario.DoesNotExist:
        context = {'user_profile': None}
    return render(request, 'dados.html', context)

def extrato_view(request):
    usuario = request.user
    try:
        perfil_usuario = PerfilUsuario.objects.get(nome=usuario)
        context = {'user_profile': perfil_usuario}
    except PerfilUsuario.DoesNotExist:
        context = {'user_profile': None}
    return render(request, 'extrato.html', context)

def pagar_view(request):
    usuario = request.user
    try:
        perfil_usuario = PerfilUsuario.objects.get(nome=usuario)
        context = {'user_profile': perfil_usuario}
    except PerfilUsuario.DoesNotExist:
        context = {'user_profile': None}
    return render(request, 'pagar.html', context)

def transferir_view(request):
    usuario = request.user
    try:
        perfil_usuario = PerfilUsuario.objects.get(nome=usuario)
        context = {'user_profile': perfil_usuario}
    except PerfilUsuario.DoesNotExist:
        context = {'user_profile': None}
    return render(request, 'transferir.html', context)

def investir_view(request):
    usuario = request.user
    try:
        perfil_usuario = PerfilUsuario.objects.get(nome=usuario)
        context = {'user_profile': perfil_usuario}
    except PerfilUsuario.DoesNotExist:
        context = {'user_profile': None}
    return render(request, 'investir.html', context)

def emprestimo_view(request):
    usuario = request.user
    try:
        perfil_usuario = PerfilUsuario.objects.get(nome=usuario)
        context = {'user_profile': perfil_usuario}
    except PerfilUsuario.DoesNotExist:
        context = {'user_profile': None}
    return render(request, 'emprestimo.html', context)

def saldo_view(request):
    context = {'user_profile': request.user}
    return render(request, 'principal.html', context)

def notificacoes_view(request):
    usuario = request.user
    try:
        perfil_usuario = PerfilUsuario.objects.get(nome=usuario)
        context = {'user_profile': perfil_usuario}
    except PerfilUsuario.DoesNotExist:
        context = {'user_profile': None}
    return render(request, 'notificacoes.html', context)

def configuracoes_view(request):
    # Lógica para lidar com um pedido POST, se necessário
    if request.method == 'POST':
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        # Lógica para atualizar os dados do usuário no banco de dados
        return redirect('dashboard:configuracoes_view')

    # Lógica para lidar com um pedido GET
    usuario = request.user
    try:
        perfil_usuario = PerfilUsuario.objects.get(nome=usuario)
        context = {'user_profile': perfil_usuario}
    except PerfilUsuario.DoesNotExist:
        context = {'user_profile': None}
    return render(request, 'configurar.html', context)

def cartoes_view(request):
    usuario = request.user
    try:
        perfil_usuario = PerfilUsuario.objects.get(nome=usuario)
        context = {'user_profile': perfil_usuario}
    except PerfilUsuario.DoesNotExist:
        context = {'user_profile': None}
    return render(request, 'cartao.html', context)

banco_comercial/principal/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
# Create your views here.
def home_view(request):
    return render(request, 'index.html')
# def login_view_redict(request):
#     # Lógica da sua view em app1

#     # Agora, vamos redirecionar para a view em contas
#     url = reverse('contas:login_view')  # Certifique-se de usar o namespace adequado
#     return redirect(url)

banco_comercial/dashboard/templates/cartao.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/cartao.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@100;200;300;400;500;600&family=Montserrat:wght@100;200;300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@100;200;300;400;500;600&family=Montserrat:wght@100;200;300;400;500;600;700;800&family=Poppins:wght@100;200;300;400;500&family=Raleway:wght@100;200;300;400;500&display=swap"
        rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@100;200;300;400;500;600&family=Montserrat:wght@100;200;300;400;500;600;700;800&family=Raleway:wght@100;200;300;400;500&display=swap"
        rel="stylesheet">
    <title>Dashboard</title>
</head>

<body>
    <script src="{% static 'dashboard/js/cartao.js' %}"></script>
    <div class="primary">
        <div class="primary_1">
            <img id="logo" src="{% static 'dashboard/img/W 1 (1).png'%}" id="logo" alt="logo" width="50px" height="40px">
            <h1 class="wiseinvest">WiseInvest</h1>
        </div>
        <div class="primary_2">
            <button type="button" id="btn_access">Acessar outra conta</button>
        </div>
    </div>
    <div class="second">
        <p class="hello">Olá, Usuario<br>
            Conta 0000-01/ Agencia 0000</p>
    </div><br>
    <div class="third">
        <div class="third_1">
            <a href="{% url 'dashboard:extrato_view' %}">
                <div class="circle">
                    <img class="image_box" src="{% static 'dashboard/img/money-check-edit (2) 1.png'%}" alt="money-check-edit" width="20px">
                </div>
                <p class="paragraf_box">Extrato</p>
            </a>
        </div>
        <div class="third_1">
            <a href="{% url 'dashboard:pagar_view' %}">
                <div class="circle">
                    <img class="image_box" src="{% static 'dashboard/img/Vector.png'%}" alt="Vector" width="20px">
                </div>
                <p class="paragraf_box">Pagar</p>
            </a>
        </div>
        
        <div class="third_1">
            <a href="{% url 'dashboard:transferir_view' %}">
                <div class="circle">
                    <img class="image_box" src="{% static 'dashboard/img/Vector (1).png'%}" alt="Vector" width="20px">
                </div>
                <p class="paragraf_box">Transferir</p>
            </a>
        </div>
        
        <div class="third_1">
            <a href="{% url 'dashboard:investir_view' %}">
                <div class="circle">
                    <img class="image_box" src="{% static 'dashboard/img/funnel-dollar 1.png'%}" alt="funnel-dollar" width="15px">
                </div>
                <p class="paragraf_box">Investir</p>
            </a>
        </div>
        
        <div class="third_1">
            <a href="#"><!-- Adicione a URL desejada para Recarga -->
                <div class="circle">
                    <img class="image_box" src="{% static 'dashboard/img/Vector (3).png'%}" alt="Vector" width="20px">
                </div>
                <p class="paragraf_box">Recarga</p>
            </a>
        </div>
        <div class="third_1">
            <div class="circle">
                <img class="image_box" src="{% static 'dashboard/img/Vector (3).png'%}" alt="Vector" width="20px">
            </div>
            <p class="paragraf_box" onclick="">Recarga</p>
        </div>
        <div class="third_1">
            <div class="circle">
                <img class="image_box" src="{% static 'dashboard/img/shopping-cart 1.png'%}" alt="shopping-cart" width="20px">
            </div>
            <p class="paragraf_box" onclick="">WiseShop</p>
        </div>
    </div><br>
    <div class="general">
        <div class="fourth">
            <div class="fourth_div"">
                <div class=" data_div">
                <img class="images_fourth" src="{% static 'dashboard/img/uil_user.png'%}" alt="uil_user">
            </div>
            <a href="{% url 'dashboard:dados_view' %}">
                <p class="text_fourth" onclick="dados()">Meus Dados</p>
                <div class=" row_div">
                <img src="{% static 'dashboard/img/Vector (4).png'%}" alt="Vector">
            </a>
        </div>
    </div>
    <div class="fourth_div">
        <div class="data_div">
            <img class="images_fourth" src="{% static 'dashboard/img/uil_sliders-v.png'%}" alt="uil_sliders-v">
        </div>
        <a href="{% url 'dashboard:configuracoes_view' %}">
            <p class="text_fourth" onclick="configurarApp()">Configurar App</p></a>
            <div class="row_div">
                <img src="{% static 'dashboard/img/Vector (4).png'%}" alt="Vector">
            </div>
    </div>
    <div class="fourth_div">
       
            <div class="data_div">
                <img class="images_fourth" src="{% static 'dashboard/img/Vector (5).png'%}" alt="Vector">
            </div>
            <a href="{% url 'dashboard:saldo_view' %}">
            <p class="text_fourth">Saldo</p></a>
            <div class="row_div">
                <img src="{% static 'dashboard/img/Vector (4).png'%}" alt="Vector">
            </div>
        
    </div>
    <div class="fourth_div">
        <div class="data_div">
            <img class="images_fourth" src="{% static 'dashboard/img/Vector (6).png'%}" alt="Vector">
        </div>
        <a href="{% url 'dashboard:notificacoes_view' %}">
        <p class="text_fourth" onclick="notificacoes()">Notificações</p></a>
        <div class="row_div">
            <img src="{% static 'dashboard/img/Vector (4).png'%}" alt="Vector">
        </div>
    </div>
    <div class="fourth_div">
        <div class="data_div">
            <img class="images_fourth" src="{% static 'dashboard/img/Vector (7).png'%}" alt="Vector">
        </div>
        <a href="{% url 'dashboard:configuracoes_view' %}">
        <p class="text_fourth" onclick="configuracoes()">Configurações</p></a>
        <div class="row_div">
            <img src="{% static 'dashboard/img/Vector (4).png'%}" alt="Vector">
        </div>
    </div>
    <div class="fourth_div">
        <div class="data_div">
            <img class="images_fourth" src="{% static 'dashboard/img/Vector (8).png'%}" alt="Vector">
        </div>
        <a href="{% url 'dashboard:cartoes_view' %}">
        <p class="text_fourth" onclick="cartoes()">Cartões</p></a>
        <div class="row_div">
            <img src="{% static 'dashboard/img/Vector (4).png'%}" alt="Vector">
        </div>
    </div>
    </div>
    <div class="general_cartao">
        <div class="cartao_debito">
            <p>Cartão de Débito</p>
            <div class="debito">
                <p>WiseDebit</p>
                <p>0000 0000 0000 0000</p>
                <p>Geovani</p>
                <p>Data de vencimento:</p>
            </div>
            <button class="bloquear_cartao">Bloquear Cartão</button>
        </div>
        <div class="cartao_credito">
            <p>Cartão de Crédito</p>
            <div class="credito">
                <p>WiseCredit</p>
                <p>0000 0000 0000 0000</p>
                <p>Geovani</p>
                <p>Data de vencimento:</p>
            </div>
            <button class="bloquear_cartao">Bloquear Cartão</button>
        </div>
    </div>
    </div>
</body>

</html>

banco_comercial/dashboard/templates/configurar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/configurar.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@100;200;300;400;500;600&family=Montserrat:wght@100;200;300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@100;200;300;400;500;600&family=Montserrat:wght@100;200;300;400;500;600;700;800&family=Poppins:wght@100;200;300;400;500&family=Raleway:wght@100;200;300;400;500&display=swap"
        rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@100;200;300;400;500;600&family=Montserrat:wght@100;200;300;400;500;600;700;800&family=Raleway:wght@100;200;300;400;500&display=swap"
        rel="stylesheet">
    <title>Dashboard</title>
</head>

<body>
    <script src="{% static 'dashboard/js/configurar.js' %}"></script>
    <div class="primary">
        <div class="primary_1">
            <img id="logo" src="{% static 'dashboard/img/W 1 (1).png'%}" id="logo" alt="logo" width="50px" height="40px">
            <h1 class="wiseinvest">WiseInvest</h1>
        </div>
        <div class="primary_2">
            <button type="button" id="btn_access">Acessar outra conta</button>
        </div>
    </div>
    <div class="second">
        <p class="hello">Olá, Usuario<br>
            Conta 0000-01/ Agencia 0000</p>
    </div><br>
    <div class="third">
        <div class="third_1">
            <a href="{% url 'dashboard:extrato_view' %}">
                <div class="circle">
                    <img class="image_box" src="{% static 'dashboard/img/money-check-edit (2) 1.png'%}" alt="money-check-edit" width="20px">
                </div>
                <p class="paragraf_box">Extrato</p>
            </a>
        </div>
        <div class="third_1">
            <a href="{% url 'dashboard:pagar_view' %}">
                <div class="circle">
                    <img class="image_box" src="{% static 'dashboard/img/Vector.png'%}" alt="Vector" width="20px">
                </div>
                <p class="paragraf_box">Pagar</p>
            </a>
        </div>
        
        <div class="third_1">
            <a href="{% url 'dashboard:transferir_view' %}">
                <div class="circle">
                    <img class="image_box" src="{% static 'dashboard/img/Vector (1).png'%}" alt="Vector" width="20px">
                </div>
                <p class="paragraf_box">Transferir</p>
            </a>
        </div>
        
        <div class="third_1">
            <a href="{% url 'dashboard:investir_view' %}">
                <div class="circle">
                    <img class="image_box" src="{% static 'dashboard/img/funnel-dollar 1.png'%}" alt="funnel-dollar" width="15px">
                </div>
                <p class="paragraf_box">Investir</p>
            </a>
        </div>
        
        <div class="third_1">
            <a href="#"><!-- Adicione a URL desejada para Recarga -->
                <div class="circle">
                    <img class="image_box" src="{% static 'dashboard/img/Vector (3).png'%}" alt="Vector" width="20px">
                </div>
                <p class="paragraf_box">Recarga</p>
            </a>
        </div>
        <div class="third_1">
            <div class="circle">
                <img class="image_box" src="{% static 'dashboard/img/Vector (3).png'%}" alt="Vector" width="20px">
            </div>
            <p class="paragraf_box" onclick="">Recarga</p>
        </div>
        <div class="third_1">
            <div class="circle">
                <img class="image_box" src="{% static 'dashboard/img/shopping-cart 1.png'%}" alt="shopping-cart" width="20px">
            </div>
            <p class="paragraf_box" onclick="">WiseShop</p>
        </div>
    </div><br>
    <div class="general">
        <div class="fourth">
            <div class="fourth_div"">
                <div class=" data_div">
                <img class="images_fourth" src="{% static 'dashboard/img/uil_user.png'%}" alt="uil_user">
            </div>
            <a href="{% url 'dashboard:dados_view' %}">
                <p class="text_fourth" onclick="dados()">Meus Dados</p>
                <div class=" row_div">
                <img src="{% static 'dashboard/img/Vector (4).png'%}" alt="Vector">
            </a>
        </div>
    </div>
    <div class="fourth_div">
        <div class="data_div">
            <img class="images_fourth" src="{% static 'dashboard/img/uil_sliders-v.png'%}" alt="uil_sliders-v">
        </div>
        <a href="{% url 'dashboard:configuracoes_view' %}">
            <p class="text_fourth" onclick="configurarApp()">Configurar App</p></a>
            <div class="row_div">
                <img src="{% static 'dashboard/img/Vector (4).png'%}" alt="Vector">
            </div>
    </div>
    <div class="fourth_div">
       
            <div class="data_div">
                <img class="images_fourth" src="{% static 'dashboard/img/Vector (5).png'%}" alt="Vector">
            </div>
            <a href="{% url 'dashboard:saldo_view' %}">
            <p class="text_fourth">Saldo</p></a>
            <div class="row_div">
                <img src="{% static 'dashboard/img/Vector (4).png'%}" alt="Vector">
            </div>
        
    </div>
    <div class="fourth_div">
        <div class="data_div">
            <img class="images_fourth" src="{% static 'dashboard/img/Vector (6).png'%}" alt="Vector">
        </div>
        <a href="{% url 'dashboard:notificacoes_view' %}">
        <p class="text_fourth" onclick="notificacoes()">Notificações</p></a>
        <div class="row_div">
            <img src="{% static 'dashboard/img/Vector (4).png'%}" alt="Vector">
        </div>
    </div>
    <div class="fourth_div">
        <div class="data_div">
            <img class="images_fourth" src="{% static 'dashboard/img/Vector (7).png'%}" alt="Vector">
        </div>
        <a href="{% url 'dashboard:configuracoes_view' %}">
        <p class="text_fourth" onclick="configuracoes()">Configurações</p></a>
        <div class="row_div">
            <img src="{% static 'dashboard/img/Vector (4).png'%}" alt="Vector">
        </div>
    </div>
    <div class="fourth_div">
        <div class="data_div">
            <img class="images_fourth" src="{% static 'dashboard/img/Vector (8).png'%}" alt="Vector">
        </div>
        <a href="{% url 'dashboard:cartoes_view' %}">
        <p class="text_fourth" onclick="cartoes()">Cartões</p></a>
        <div class="row_div">
            <img src="{% static 'dashboard/img/Vector (4).png'%}" alt="Vector">
        </div>
    </div>
    </div>
    <div class="configurar_conta">
        <h1 id="texto_configurar">Configurar Conta</h1>
        <div class="div_configurar_conta">
            <div class="div_informacoes">
                <p class="informacoes">Nome:</p><br>
                <p class="informacoes">E-mail:</p><br>
                <p class="informacoes">Endereço:</p>
            </div>
            <div class="div_informacoes">
                <p class="informacoes">Chaves Pix Cadastradas:</p>
                <p class="informacoes">Cadastrar Nova Chave Pix:</p>
            </div>
        </div>
    </div>
    </div>
</body>

</html>