banco_comercial/banco_comercial/urls.py
from django.contrib import admin
from django.urls import include, path
from principal import urls as principal_urls 
urlpatterns = [
    path("user/", include("contas.urls", namespace='contas')),
    path("admin/", admin.site.urls),
    path('', include((principal_urls, 'principal'), namespace='principal')),
    path('client/', include('dashboard.urls', namespace='dashboard')),

]

banco_comercial/contas/urls.py
from django.urls import path
from .views import cadastro_view, poscadastro_view,redict_home, login_view
app_name = 'contas'
urlpatterns = [
    path('cadastro/', cadastro_view, name='cadastro_view'),
    path('pos/', poscadastro_view, name='poscadastro_view'),
    path('login/', login_view, name='login_view'),
    path('redict_home/', redict_home, name='redict_home'),

    # ... outras URLs ...
]

banco_comercial/contas/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models

class PerfilUsuarioManager(BaseUserManager):
    def create_user(self, email, nome, password=None, **extra_fields):
        if not email:
            raise ValueError('O campo de e-mail deve ser definido')
        email = self.normalize_email(email)
        user = self.model(email=email, nome=nome, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nome, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, nome, password, **extra_fields)
    
    def authenticate(self, request, email=None, password=None, **kwargs):
        # Implemente a lógica de autenticação personalizada aqui
        try:
            user = self.get(email=email)
        except self.model.DoesNotExist:
            return None

        if user.check_password(password):
            return user
class PerfilUsuario(AbstractBaseUser, PermissionsMixin):
    nome = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    senha = models.CharField(max_length=100)
    telefone = models.CharField(max_length=15, blank=True, null=True)
    rg = models.CharField(max_length=20, blank=True, null=True)
    cpf = models.CharField(max_length=11, unique=True)
    data_nascimento = models.DateField(blank=True, null=True)
    cep = models.CharField(max_length=10, blank=True, null=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = PerfilUsuarioManager()

    USERNAME_FIELD = 'email'

    # Adicione ou altere o related_name para evitar conflitos
    groups = models.ManyToManyField(
        'auth.Group',
        blank=True,
        related_name='perfil_usuarios_groups',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        blank=True,
        related_name='perfil_usuarios_permissions',
    )

    def __str__(self):
        return self.nome

# class PerfilUsuario(models.Model):
#     nome = models.CharField(max_length=100)
#     email = models.EmailField(unique=True)
#     telefone = models.CharField(max_length=15, blank=True, null=True)
#     senha = models.CharField(max_length=100)
#     rg = models.CharField(max_length=20, blank=True, null=True)
#     cpf = models.CharField(max_length=11, unique=True)
#     data_nascimento = models.DateField(blank=True, null=True)
#     cep = models.CharField(max_length=10, blank=True, null=True)

#     def __str__(self):
#         return self.nome
    

banco_comercial/contas/forms.py
from django import forms
from .models import PerfilUsuario
from django.core.exceptions import ValidationError

class CadastroForm(forms.ModelForm):
    confirmar_senha = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = PerfilUsuario
        fields = ['nome', 'email', 'telefone', 'senha', 'confirmar_senha', 'rg', 'cpf', 'data_nascimento', 'cep']
    def clean(self):
        cleaned_data = super().clean()
        senha = cleaned_data.get('senha')
        confirmar_senha = cleaned_data.get('confirmar_senha')

        if senha and confirmar_senha and senha != confirmar_senha:
            raise ValidationError("As senhas não correspondem. Por favor, verifique.")

        return cleaned_data

banco_comercial/contas/views.py
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.urls import reverse
from .forms import CadastroForm
from .models import PerfilUsuario, PerfilUsuarioManager


# Create your views here.

def cadastro_view(request):
    if request.method == 'POST':
        form = CadastroForm(request.POST)
        if form.is_valid():
            form.save()
            # Lógica após o salvamento bem-sucedido
            return redirect('contas:login_view')
    else:
        form = CadastroForm()

    return render(request, 'cadastro.html', {'form': form})

    
def poscadastro_view(request):
    # Lógica para a página pós-cadastro aqui
    return render(request, 'poscadastro.html')



def login_view(request):
    if request.method == 'POST':
        
        
        email = request.POST.get('input_email')
        senha = request.POST.get('input_password')
        # print(PerfilUsuario.objects.filter(email=email).exists() and PerfilUsuario.objects.filter(senha=senha).exists())
        if PerfilUsuario.objects.filter(email=email).exists() and PerfilUsuario.objects.filter(senha=senha).exists() :
            emaiBanco = PerfilUsuario.objects.get(email=email).email
            user = PerfilUsuario.objects.authenticate(request, email=emaiBanco, password=senha)
            
            print(f"USER ESTÁ FUNCIONANDO OU NÃO: {user}")
            if user is not None:
                print("Autenticou")
                login(request, user)
                # Redireciona para a URL nomeada da view do dashboard
                print(reverse('dashboard:saldo_view'))

            return redirect('/client/saldo/')
        else:
            print("Não Autenticou")
            messages.error(request, 'Credenciais inválidas. Tente novamente.')

    return render(request, 'login.html')

def redict_home(request):
    # Lógica adicional, se necessário
    # ...
    url = reverse('principal:home_view')
    # Redireciona para a view do outro app
    return redirect(url)
@login_required
def dashboard_view(request):
    # Adicione lógica adicional conforme necessário
    return render(request, 'dashboard/dashboard.html')

banco_comercial/contas/templates/cadastro.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'contas/css/style_cadastro.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <title>Registro</title>
    <!-- <script src="app3.js" defer> -->

    </script>
</head>

<body>
    <div class="logo_marca">
        <img src="{% static 'contas/img/imagens_cadastro/W 1.png' %}" id="logo" alt="logo" width="50px">
        <h1 id="wiseinvest">WiseInvest Bank</h1>
    </div>
    <h2 id="informacoes_registro">Faça seu registro preenchendo as informações abaixo:</h2>
    <div class="div_general">
        <img src="{% static 'contas/img/imagens_cadastro/Component 1.png'%}" id="imagem1" alt="pessoa no celular">
        <div class="div_cadastro">
            
              
            <form id="form"method="post" action="{% url 'contas:cadastro_view' %}">
                {% csrf_token %}
                <div class="inputs">
                    <div class="input">
                        <img src="{% static 'contas/img/imagens_cadastro/user (1) 1.png'%}" id="usuario_icone" alt="usuario">
                        <input type="text" name="nome" id="nome" placeholder="Nome Completo" required>
                    </div>
                    <div class="input">
                        <img src="{% static 'contas/img/imagens_cadastro/envelope 1.png'%}" id="envelope_icone" alt="envelope">
                        <input type="email" name="email" id="email" placeholder="E-mail" required>
                    </div>
                    <div class="input">
                        <img src="{% static 'contas/img/imagens_cadastro/phone-call 1.png'%}" id="telefone_icone"
                            alt="telefone">
                        <input type="phone" name="tel" id="telefone" placeholder="Telefone" required>
                    </div>
                    <div class="input">
                        <img src="{% static 'contas/img/imagens_cadastro/lock 1.png'%}" id="cadeado_1" alt="cadeado">
                        <input type="password" name="senha" id="senha" placeholder="Senha" required>
                    </div>
                    <div class="input">
                        <img src="{% static 'contas/img/imagens_cadastro/lock 3.png'%}" id="cadeado_2" alt="cadeado">
                        <input type="password" name="confirmar_senha" id="confirmar_senha" placeholder="Confirmar Senha" required>
                    </div>
                    <div class="input">
                        <img src="{% static 'contas/img/imagens_cadastro/folder 1.png'%}" id="pasta_icone" alt="pasta">
                        <input type="number" name="rg" id="rg" placeholder="RG" required>
                    </div>
                    <div class="input">
                        <img src="{% static 'contas/img/imagens_cadastro/memo-circle-check 1.png'%}" id="pasta_cpf"
                            alt="pasta">
                        <input type="number" name="cpf" id="cpf" placeholder="CPF" required>
                    </div>
                    <div class="input">
                        <img src="{% static 'contas/img/imagens_cadastro/calendar 1.png'%}" id="calendario" alt="calendario">
                        <input type="date" name="data" id="data" placeholder="Data de Nascimento" required>
                    </div>
                    <div class="input">
                        <img src="{% static 'contas/img/imagens_cadastro/map-marker 1.png'%}" id="mapa" alt="mapa">
                        <input type="number" name="cep" id="cep" placeholder="CEP" required>
                    </div>
                </div>
                <input  id="botao" type="submit" value="Cadastrar">
                {% if form.errors %}
                <ul class="errorlist">
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                            <li>{{ field|title }}: {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
                {% endif %}
            </form>
        </div>
        <img src="{% static 'contas/img/imagens_cadastro/Component 2.png'%}" id="imagem2" alt="pessoa no computador">
    </div>
</body>

</html>

banco_comercial/contas/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'contas/css/style_login.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <title>Login</title>
</head>

<body>
    
    <main>
        <div class="div_primary">
            <div class="marca">
                <img id="logo" src="{% static 'contas/img/imagens_login/W 1.png' %}" alt="logo">
                <h1 id="name">WiseInvest Bank</h1>
                <h2 id="name_2">INVESTIMENTO INTELIGENTE</h2>
            </div>
            <p id="paragraf">Na WiseInvest, buscamos democratizar o
                investimento, oferencendo soluções
                inteligentes e acessíveis, para impulsionar o
                sucesso financeiro de nossos clientes.</p>
            <div class="second_images">
                <img id="man" src="{% static 'contas/img/imagens_login/presentation 1.png'%}" alt="homem mostrando graficos">
                <img id="woman" src="{% static 'contas/img/imagens_login/project-management 1.png'%}"
                    alt="mulher mostrabdo graficos">
            </div>
        </div>
        <form id="form" method="post" action="{% url 'contas:login_view' %}">
            {% csrf_token %}
            <h2 id="acess">Acesse sua conta!</h2>
            <div class="inputs_form">
                <div class="login_form">
                    <label for="input_email">Login</label>
                    <input id="input_email" name="input_email" type="email" placeholder="E-mail" required>
                </div>
                <div class="form_password">
                    <label for="input_password">Senha</label>
                    <input id="input_password" name="input_password" type="password" placeholder="Senha" required>
                    <a id="forgot_password" href="">Esqueceu a senha?</a>
                </div>
            </div>
            <button type="submit" id="button_submit">Enviar</button>
            <div class="account_form">
                <p id="havent_account">Ainda não possui uma conta?</p>
                <a href="{% url 'contas:cadastro_view' %}"><button type="button" id="create_account">Abrir uma conta</button></a>
            </div>
        </form>
        
    </main>
    <!-- <script src="{% static 'contas/js/app2.js' %}"></script> -->
</body>

</html>

banco_comercial/contas/templates/poscadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'contas/css/style_poscadastro.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@100;200;300;400;500;600&family=Montserrat:wght@100;200;300;400;500;600;700;800&family=Poppins:wght@100;200;300;400;500&family=Quicksand:wght@300;400&family=Raleway:wght@100;200;300;400;500&display=swap"
        rel="stylesheet">
    <title>Dados</title>
</head>

<body>
    <script src="app4.js">

    </script>
    <div id="container">
        <img class="image" src="{% static 'contas/img/imagens/design-software 1.png' %}" alt="design-software">
        <div class="container_text">
            <div class="text_top">
                <h1>Seus dados foram enviados!</h1>
                <img src="{% static 'contas/img/imagens/check-circle 2.png' %}" id="check" alt="check-circle" width="30px">
                <h3>Nosso sistema recebeu seus dados com<br>
                    sucesso. Agora iremos analisar e em breve<br>
                    retornaremos com uma mensagem.</h3>
                <h3>Verifique seu e-mail!</h3>
                <a href="{% url 'contas:redict_home' %}">Clique aqui para voltar</a>
            </div>
        </div>
        <img class="image" src="{% static 'contas/img/imagens/mental-health 1.png' %}" alt="mental-health" >
    </div>
</body>

</html>